### ISSUE TITLE
I cannot play deezer playlist

### ISSUE THREAD

**Issue by byorage** [distubejs/deezer#1]
**Please describe your problem in as much detail as possible:** when i execute my command to play a song and i enter the link of the deezer playlist, the bot report me the following error : "An error encountered: DisTubeError [YTDLP_ERROR]: Cannot get stream URL of a entire playlist" i think you need to update it

**Further information:* everything is above

- Plugin version: 1.0.0
- DisTube version: 4.1.1
- discord.js version: 14.14.1
- Node.js version: 18
- Operating system: Pterodactyl server

![image](https://github.com/distubejs/deezer/assets/97020413/0a1280c9-1ecb-43b1-9396-ae3140ef2cda)

**Comment by skick1234** [comment]
Please provide your link and the code of your DisTube contrustor `new DisTube(...)`

**Comment by byorage** [comment]
Is that what you want?
``` javascript
client.config = config;
client.player = new DisTube(client, {
  leaveOnStop: config.opt.voiceConfig.leaveOnStop,
  leaveOnFinish: config.opt.voiceConfig.leaveOnFinish,
  leaveOnEmpty: config.opt.voiceConfig.leaveOnEmpty.status,
  emitNewSongOnly: true,
  emitAddSongWhenCreatingQueue: false,
  emitAddListWhenCreatingQueue: false,
  plugins: [
    new SpotifyPlugin(),
    new SoundCloudPlugin(),
    new YtDlpPlugin(),
    new DeezerPlugin(),
  ],
});
```

if the link you wish to have is the playlist link, then here is: https://deezer.page.link/g6gxzGqVnZFbmcPm9

**Comment by skick1234** [comment]
ytdlp plugin must be the last plugin in the plugins array, I will update in its docs later.

**Comment by byorage** [comment]
If I put it like this, does it solve the problem?
``` javascript
client.config = config;
client.player = new DisTube(client, {
  leaveOnStop: config.opt.voiceConfig.leaveOnStop,
  leaveOnFinish: config.opt.voiceConfig.leaveOnFinish,
  leaveOnEmpty: config.opt.voiceConfig.leaveOnEmpty.status,
  emitNewSongOnly: true,
  emitAddSongWhenCreatingQueue: false,
  emitAddListWhenCreatingQueue: false,
  plugins: [
    new SpotifyPlugin(),
    new DeezerPlugin(),
    new SoundCloudPlugin(),
    new YtDlpPlugin(),
  ],
});
```

**Comment by byorage** [comment]
Hey, I did what you told me to do and I still have the same problem!
Do you have another solution?

**Comment by skick1234** [comment]
`deezer.page.link` is
not a deezer link. It redirects to a `deezer.com` link which is a deezer link and supported by the plugin.

**Comment by byorage** [comment]
Yes but that’s what deezer gives me when I click on the music and then on share so how do I do it?
